01_AspNetMVC/01_AspNetMVC/ViewModels/ContactFormViewModel.cs
using _01_AspNetMVC.models.DTO;
using System.ComponentModel.DataAnnotations;

namespace _01_AspNetMVC.ViewModels
{
    public class ContactFormViewModel
    {
        [Required(ErrorMessage = "You must enter your name")]
        public string Name { get; set; } = null!;

        [Required(ErrorMessage = "You must enter a valid email address")]
        [MinLength(5)]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid email")]
        [EmailAddress]
        public string Email { get; set; } = null!;

        [Required(ErrorMessage = "Don't forget to write your message")]
        public string Comment { get; set; } = null!;

        public string ConfirmationMsg { get; set; } = "";


        public static implicit operator CustomerCommentDTO(ContactFormViewModel model)
        {
            return new CustomerCommentDTO
            {
                Name = model.Name,
                Email = model.Email,
                Comment = model.Comment,
            };
        }

    }
}

01_AspNetMVC/01_AspNetMVC/ViewModels/HomeViewViewModel.cs
using _01_AspNetMVC.models.DTO;
using _01_AspNetMVC.Models;

namespace _01_AspNetMVC.ViewModels
{
    public class HomeViewViewModel
    {
        public ShowcaseDTO ShowcaseDTO { get; set; } = null!;
        public IEnumerable<CollectionItemModel> Featured { get; set; } = new List<CollectionItemModel>();
        public IEnumerable<CollectionItemModel> New { get; set; } = new List<CollectionItemModel>();
        public IEnumerable<CollectionItemModel> Popular { get; set; } = new List<CollectionItemModel>();
    }
}

01_AspNetMVC/01_AspNetMVC/ViewModels/LoginFormViewModel.cs
using _01_AspNetMVC.models.DTO;
using System.ComponentModel.DataAnnotations;

namespace _01_AspNetMVC.ViewModels
{
    public class LoginFormViewModel
    {
        [Required(ErrorMessage = "Field is required")]
        [EmailAddress]
        public string Email { get; set; } = null!;

        [Required(ErrorMessage = "Field is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; } = null!;

        public static implicit operator LoginDTO(LoginFormViewModel model)
        {
            return new LoginDTO
            {
                Email = model.Email,
                Password = model.Password,
            };
        }
    }
}

01_AspNetMVC/01_AspNetMVC/ViewModels/RegisterFormViewModel.cs
using _01_AspNetMVC.models.DTO;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace _01_AspNetMVC.ViewModels
{
    public class RegisterFormViewModel
    {
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "This field is required")]
        [MinLength(2, ErrorMessage = "Must contain atleast 2 characters")]
        public string FirstName { get; set; } = null!;

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "This field is required")]
        [MinLength(2, ErrorMessage = "Must contain atleast 2 characters")]
        public string LastName { get; set; } = null!;

        [Display(Name = "Email")]
        [EmailAddress]
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Not a valid email")]
        public string Email { get; set; } = null!;

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression(@"^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[^a-zA-Z0-9]).{8,}$", ErrorMessage = "Not a valid password")]
        [DataType(DataType.Password)]
        public string Password { get; set; } = null!;

        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare(nameof(Password), ErrorMessage = "The passwords don't match")]
        public string ConfirmPassword { get; set; } = null!;
        
        public static implicit operator RegisterUserDTO(RegisterFormViewModel model)
        {
            return new RegisterUserDTO
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                Password = model.Password,
            };
        }
    }
}

01_AspNetMVC/01_AspNetMVC/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace _01_AspNetMVC.Controllers;

public class AboutController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

01_AspNetMVC/01_AspNetMVC/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace _01_AspNetMVC.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateAccount()
        {
            return View();
        }
    }
}

01_AspNetMVC/01_AspNetMVC/Controllers/ContactController.cs
using _01_AspNetMVC.models.DTO;
using _01_AspNetMVC.Services;
using _01_AspNetMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace _01_AspNetMVC.Controllers;

public class ContactController : Controller
{
    private readonly CustomerSupportServices _services;

    public ContactController(CustomerSupportServices services)
    {
        _services = services;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Index(ContactFormViewModel model)
    {
        if (ModelState.IsValid)
        {
            var result = await _services.SaveCommentAsync(model);

            if (result.StatusCode == System.Net.HttpStatusCode.Created)
            {
                ModelState.Clear();
                model = new ContactFormViewModel()
                {
                    ConfirmationMsg = "Thank you for your message. Our customer support will hopefully be responsive within a fortnight"
                };
                return View(model);
            }
            
            model.ConfirmationMsg = "Oops, something went bellyup here. Please try again, if this happens again the server might have deemed your comment as trash.";
            return View(model);
        }
        
        return View(model);
    }
}

01_AspNetMVC/01_AspNetMVC/Controllers/HomeController.cs
using _01_AspNetMVC.Services;
using _01_AspNetMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace _01_AspNetMVC.Controllers;

public class HomeController : Controller
{
    private readonly ProductService _productService;
    private readonly ShowcaseService _showcaseService;

    public HomeController(ProductService productService, ShowcaseService showcaseService)
    {
        _productService = productService;
        _showcaseService = showcaseService;
    }

    public async Task<IActionResult> Index()
    {
        var showcase = await _showcaseService.GetLatestShowcaseAsync();
        var featuredProducts = await _productService.GetByTagAsync("Featured");
        featuredProducts = featuredProducts.Take(8).ToList();
        var newProducts = await _productService.GetByTagAsync("New");
        newProducts = newProducts.Take(6).ToList();
        var popularProducts = await _productService.GetByTagAsync("Popular");
        popularProducts = popularProducts.Take(6).ToList();
        HomeViewViewModel model = new HomeViewViewModel
        {
            ShowcaseDTO = showcase,
            Featured = featuredProducts,
            New = newProducts,
            Popular = popularProducts,
        };

        return View(model);
    }
}

01_AspNetMVC/01_AspNetMVC/Controllers/ProductController.cs
using _01_AspNetMVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace _01_AspNetMVC.Controllers;

public class ProductController : Controller
{
    private readonly ProductService _productService;

    public ProductController(ProductService productService)
    {
        _productService = productService;
    }

    public async Task<IActionResult> Index()
    {
        var productList = await _productService.GetAllAsync();
        return View(productList);
    }

    public async Task<IActionResult> Details(int id)
    {
        var product = await _productService.GetByIdAsync(id);
      
        return View(product);
    }
}

01_AspNetMVC/01_AspNetMVC/Views/Contact/Index.cshtml
<partial name="_MapPartial" />
<partial name="_ContactFormPartial" />

01_AspNetMVC/01_AspNetMVC/Views/Contact/_ContactFormPartial.cshtml
@model ContactFormViewModel

<div class="container mt-5">
    <h2 class="text-center mb-5">Come in Contact with Us</h2>   
    <form method="post" asp-action="Index" novalidate>
        <div class="row mb-3">
            <div class="col">
                <input asp-for="Name" type="text" placeholder="Your Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Name" ></span>
            </div>
            <div class="col">
                <input asp-for="Email" type="text" placeholder="Your Email" class="form-control" />
                <span class="text-danger" asp-validation-for="Email"></span>
            </div>
        </div>
        <div class="row">
            <textarea asp-for="Comment" placeholder="Your Message" class="form-control" rows="4" style="resize: none"></textarea>
            <span class="text-danger" asp-validation-for="Comment"></span>
        </div>

        <div class="row">
            <div class="col">
                <button type="submit" class="btn-theme mt-4 mb-5">Send Message</button>
            </div>
            <div class="col">
                <h3 class="text-normal text-center text-info mt-5 mb-5">@Model?.ConfirmationMsg</h3>
            </div>
        </div>
    </form>
</div>

01_AspNetMVC/01_AspNetMVC/Views/Contact/_MapPartial.cshtml
<div class="mt-5">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d27378.084815970204!2d18.0640251104274!3d59.3348182097563!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sse!4v1681730598547!5m2!1sen!2sse" width="100%" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

01_AspNetMVC/01_AspNetMVC/Views/Home/Index.cshtml
@model HomeViewViewModel

<partial name="~/Views/Partials/_ShowcasePartial.cshtml" model="Model.ShowcaseDTO" />
<partial name="~/Views/Partials/_CollectionPartial.cshtml" model="Model.Featured" />
<partial name="~/Views/Partials/_SpecialOffersPartial.cshtml" />
<partial name="~/Views/Partials/_TwoColumnCollectionNewPartial.cshtml" model="Model.New" />
<partial name="~/Views/Partials/_TwoColumnCollectionPopularPartial.cshtml" model="Model.Popular" />

01_AspNetMVC/01_AspNetMVC/Views/Partials/_CollectionItemPartial.cshtml
@model CollectionItemModel

<div class="item">
    <div class="image-section">
        <img src="~/images/blackCoat.png" alt="a simple black coat, looks cheap..." />
        <div class="menu">
            <div class="icons">
                <button class="link"><i class="fa-regular fa-code-compare"></i></button>
                <button class="link"><i class="fa-regular fa-heart"></i></button>
                <button class="link"><i class="fa-regular fa-bag-shopping"></i></button>
            </div>
            <a class="btn-theme" asp-controller="Product" asp-action="Details" asp-route-id="@Model.Id">QUICK VIEW</a>
        </div>
    </div>
    <div class="body-section">
        <div class="category">@Model?.Category</div>
        <div class="name">@Model?.Title</div>
        <partial name="~/Views/Partials/_StarRatingPartial.cshtml" model="Model?.StarRating" />
        <div class="price">$@Model?.Price</div>
    </div>
</div>

01_AspNetMVC/01_AspNetMVC/Views/Partials/_CollectionPartial.cshtml
@model IEnumerable<CollectionItemModel>

@if (Model != null)
{
    <section class="collection-grid">
        <div class="container">
            <div class="title">@ViewData["Title"]</div>
            <div class="item-collection">

                @foreach (var item in Model)
                {
                    <partial name="~/Views/Partials/_CollectionItemPartial.cshtml" model="item" />
                }
            </div>S
        </div>
    </section>
}
else
{
    <section class="collection-grid">
        <div class="container">
            <div class="title">@ViewData["Title"]</div>
            <div class="item-collection">
               <div class="title-3">Come back later for some great products</div>
            </div>
        </div>
    </section>
}

01_AspNetMVC/01_AspNetMVC/Views/Partials/_FooterPartial.cshtml
<footer class="footer">
    <p class="fw-semibold text-center">&copy; @DateTime.Now.Year Fixxo. All rights reserved.</p>
</footer>

01_AspNetMVC/01_AspNetMVC/Views/Partials/_HeaderPartial.cshtml
<header>
    <div class="container">
        <a id="logotype" href="/">Fixxo.</a>

        <div id="menu" class="">
            <nav class="menu-links links">
                <a class="link" href="/">Home</a>
                <a class="link" asp-controller="Product" asp-action="Index">Products</a>
                <a class="link" asp-controller="Contact" asp-action="Index">Contacts</a>
            </nav>
            <nav class="menu-icons icons">
                <a class="link" href="/search"><i class="fa-regular fa-search"></i></a>
                <a class="link" href="/compare"><i class="fa-regular fa-code-compare"></i></a>
                <a class="link" href="favorites"><i class="fa-regular fa-heart"></i></a>
                <a class="link" href="/cart"><i class="fa-regular fa-bag-shopping"></i></a>
                <a class="link ms-5" asp-controller="/Account" asp-action="Index"><i class="fa-regular fa-user"></i></a>
            </nav>
        </div>
        <div id="toggle-icon" class="icons">
            <button class="link" data-option="menuToggle" data-target="#menu"><i class="fa-regular fa-bars"></i></button>
        </div>
    </div>
</header>

01_AspNetMVC/01_AspNetMVC/Views/Partials/_ShowcasePartial.cshtml
@model ShowcaseDTO

@if (Model != null)
{
    <section class="showcase">
        <div class="container">
            <div class="content">
                <div class="title-2">@Model.Offer</div>
                <div class="title-1">@Model.Title?</div>
                <div class="title-3">@Model.Message?</div>
                <a class="btn-theme" href="">SHOP NOW</a>
            </div>
            <img src=@Model.ImgURL? alt="Showcase Picture" />
        </div>
    </section>
}
else
{
    <section class="showcase">
        <div class="container">
            <div class="content">
                <div class="title-2">Great offer</div>
                <div class="title-1">What it's all about</div>
                <div class="title-3">Great stuff to be found in this shop</div>
                <a class="btn-theme" href="">SHOP NOW</a>
            </div>
            <img src="~/images/showcase-img.png" alt="Showcase Picture" />
        </div>
    </section>
}

01_AspNetMVC/01_AspNetMVC/Views/Partials/_SpecialOffersPartial.cshtml
<div class="offer-grid container-fluid">
    <img id="office-style" src="~/images/office-style.png" alt="Proper office style for all your proffessional needs" />

    <div class="offer">
        <div class="red-border">
            <div class="content">
                <h1>50% Offer</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, ipsam quo voluptatum facere iure fuga. Necessitatibus quasi voluptatem delectus nam?</p>
                <button class="btn-white">FLASH SALE</button>
            </div>
        </div>
    </div>
    <img id="party-style" src="~/images/party-style.png" alt="Outgoing party style, when you feel the oumpfh coming on" />
</div>

01_AspNetMVC/01_AspNetMVC/Views/Partials/_StarRatingPartial.cshtml
@model int

<div class="star-rating">
    @for(int i = 0; i < 5; i++)
    {
        string starRating = Model >= i ? "fa-solid" : "fa-regular";

        <i class="fa-sharp fa-star @starRating"></i>
    }
</div>

01_AspNetMVC/01_AspNetMVC/Views/Partials/_TwoColumnCollectionNewPartial.cshtml
@model IEnumerable<CollectionItemModel>

<section class="collection-twocolumns">
    <div class="column bg-gray mt-5">
        <div class="content">
            <h1>2 FOR USD $29</h1>
            <button class="btn-white">NEW PRODUCTS</button>
        </div>
    </div>
    <div class="column">
        <div class="column item-collection">
            @foreach (var item in Model)
            {
                <partial name="~/Views/Partials/_CollectionItemPartial.cshtml" model="item" />

            }
        </div>
    </div>
</section>

01_AspNetMVC/01_AspNetMVC/Views/Partials/_TwoColumnCollectionPopularPartial.cshtml
@model IEnumerable<CollectionItemModel>

<section class="collection-twocolumns">
    <div class="column bg-gray mt-5">
        <div class="column item-collection">
            @foreach (var item in Model)
            {
                <partial name="~/Views/Partials/_CollectionItemPartial.cshtml" model="item" />

            }
        </div>
        <div class="content">
            <h1>2 FOR USD $29</h1>
            <button class="btn-white">NEW PRODUCTS</button>
        </div>
    </div>
</section>

01_AspNetMVC/01_AspNetMVC/Views/Product/Details.cshtml
@model CollectionItemModel

<div class="product-details">
    <div class="item collection-twocolumns mt-5">
        <div class="image-section column">
            @if (Model.ImageUrl == null)
            {
                <img src="~/images/blackCoat.png" alt="placeholder image" />
            }
            else
            {
                 <img src="@Model.ImageUrl" alt="" />
            }
        </div>
        <div class="body-section mt-5">
                <div class="category-detail">@Model?.Category</div>
                <div class="title-detail">@Model?.Title</div>
                <partial name="~/Views/Partials/_StarRatingPartial.cshtml" model="@Model?.StarRating" />
                <div class="price-detail">$@Model?.Price</div>
                <p class="fw-medium mt-5 mb-5 description-detail">@Model?.Description</p>
                <button class="btn-theme">ADD TO CART</button>
        </div>
    </div>
</div>

01_AspNetMVC/01_AspNetMVC/Views/Product/Index.cshtml
@model IEnumerable<CollectionItemModel>

<partial name="~/Views/Partials/_CollectionPartial.cshtml" model="Model"/>

01_AspNetMVC/01_AspNetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://kit.fontawesome.com/41c8b474e2.css" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>@ViewData["Title"] - _01_AspNetMVC</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <partial name="~/Views/Partials/_HeaderPartial.cshtml" />
    @RenderBody()
    <partial name="~/Views/Partials/_FooterPartial.cshtml" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>